### ISSUE TITLE
Newspaper Style

### ISSUE THREAD

**Issue by Occult-Dev** [StuffBySpencer/how-about-this-design#11]
# Inspiration:
* https://www.smashingmagazine.com/2008/11/newspaper-website-design-trends-and-examples/
* https://www.awwwards.com/newspaper-inspired-websites.html
* https://www.itsguru.com/online-magazines-news-website-designs/

***looking for more "plain & simple" + "black & white" type of designs with this one***

**Comment by galvc** [comment]
Hi, can I work on this one?

**Comment by Occult-Dev** [comment]
You sure can! Good luck, let me know if you have any questions :^)
