### ISSUE TITLE
Material Design Style

### ISSUE THREAD

**Issue by Occult-Dev** [StuffBySpencer/how-about-this-design#12]
# Inspiration:
* ***OBVIOUSLY THE BEST LINK:*** https://material.io/design/
* https://material.io/develop/web/
* https://getmdl.io/showcase/index.html
* https://www.mockplus.com/blog/post/material-design-website-examples
* https://www.cssdesignawards.com/website-gallery?feature=material+design
* http://materialdesignblog.com/material-design-showcase/
* https://madewithmaterial.tumblr.com/

**Comment by vishalthakur08** [comment]
I'm working on this.

**Comment by Occult-Dev** [comment]
Great! Let me know if you have any questions :^)

**Comment by SamRTheDev** [comment]
Started working on this throughout the day and just made a pull request Spencer! 😄

**Comment by Occult-Dev** [comment]
@vishalthakur08 Sam just submitted his PR, if you'd like to continue working on yours feel free & I can still add it to the site as a duplicate / alternative view :^)

It's up to you though!
