### ISSUE TITLE
Pixel Art Style

### ISSUE THREAD

**Issue by saguins** [StuffBySpencer/how-about-this-design#15]
I would like to suggest a Pixel Art Style, separate from Cartoon Style and Retro Style. I would love to do this!

# Inspiration:
* https://en.wikipedia.org/wiki/Pixel_art
* https://www.creativebloq.com/illustration/examples-pixel-art-2132036
* [pixel art wallpaper](https://www.pinterest.com/search/pins/?rs=ac&len=2&q=pixel%20art%20wallpaper&eq=pixel%20art&etslf=5241&term_meta[]=pixel%7Cautocomplete%7C3&term_meta[]=art%7Cautocomplete%7C3&term_meta[]=wallpaper%7Cautocomplete%7C3) on Pinterest

**Comment by Occult-Dev** [comment]
Lol this is awesome, I actually wrote down a pixel-art style in my plans for this site, I'm glad others are thinking the same thing. Would love to see this, thank you for the suggestion! :^)
