### ISSUE TITLE
Vaporwave Style

### ISSUE THREAD

**Issue by Occult-Dev** [StuffBySpencer/how-about-this-design#4]
# VAPORWAVE
* https://en.wikipedia.org/wiki/Vaporwave
* https://www.behance.net/gallery/45267045/GRAPHIC-DESIGN-Vaporwave-Poster
* https://neocities.org/browse?tag=vaporwave
* https://www.pinterest.com/genuinefraud303/vaporwave/
* https://medium.com/@JeremyCummings3/vaporwave-is-more-than-just-music-its-a-new-way-to-approach-new-ideas-6ede95452108
* https://medium.com/@ShahriyerShuvo/rise-of-vaporwave-memphis-and-brutalism-in-design-54c27583246b

**Comment by Visual-mov** [comment]
I think I'll try this one. Do I create the css myself, or is there something I'm missing?

**Comment by Occult-Dev** [comment]
@Visual-mov Hi there! Yes, you would copy the `index.html` file from the root directory, then make a `vaporwave` folder within the `styles` folder, and create your css.

We have a [**CONTRIBUTING.md**](https://github.com/StuffBySpencer/how-about-this-design/blob/master/CONTRIBUTING.md) file that should give a bit more info & guidance on how to create a design style.

Let me know if you have any questions or hold-ups, thanks!

**Comment by Occult-Dev** [comment]
#7 got a good base layer in, I'll spend some time over the next couple of days or so and touch up the font style.

Thanks! :^)
