### ISSUE TITLE
CSS Frameworks

### ISSUE THREAD

**Issue by KeziahMoselle** [StuffBySpencer/how-about-this-design#8]
Hi !
This projects looks cool !

However I have a question, is it possible to use a CSS framework to help us ?
I wanted to add Material Design but I didn't want to waste too much time when there is already a good solution for it.

I'm telling you that because of this rule :
> KEEP YOUR FILES TO A MINIMUM

Cheers

**Comment by Occult-Dev** [comment]
Yup! You're allowed to use a framework. The "minimum files" rule is mostly just to remind you to optimize when you're ready to open up a PR.

Some people like to have dozens of `.css` files while developing, but I'd recommend to concat them into one when you're ready to release.

CSS frameworks can indeed help speed up & enforce cleaner styles, so feel free to use one! :^) (*I'll add this clarification to the `CONTRIBUTING.md` doc, thanks!*)

**Comment by KeziahMoselle** [comment]
Thank you for the clarifications !
