### ISSUE TITLE
Cartoon Style

### ISSUE THREAD

**Issue by Occult-Dev** [StuffBySpencer/how-about-this-design#9]
# Inspiration:
* https://junoteam.com/blog/articles/20-cartoon-style-website-designs-inspirations/
* https://line25.com/inspiration/cartoon-style-design
* https://wptidbits.com/webs/36-cartoon-style-website-design-for-inspirations/
* https://designmodo.com/cartoon-website-designs/
* https://www.noupe.com/inspiration/showcases/showcase-of-cartoon-style-web-designs.html

**Comment by AndChurchville** [comment]
Hi I would like to work on the cartoon style!

**Comment by Occult-Dev** [comment]
Awesome! Let me know if you have any questions, thanks!

**Comment by Occult-Dev** [comment]
@AndChurchville Hi there, just checking in to see if you're still actively working on this. If not, no biggie, I just want to know whether or not I should take over.

Please let me know where you at within the next 7 days, otherwise, I'll be contributing this style. Thanks! :^)

**Comment by AndChurchville** [comment]
Hey I apologized for the long wait! Been busy with life. I'll have it in by tomorrow if that's okay!

**Comment by Occult-Dev** [comment]
No problem, take as much time as you need! I was just making sure you still wanted this grab.

Thank you for your work, and again, take as much time as you need :^)

**Comment by Occult-Dev** [comment]
**Great job @AndChurchville!**
